In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./datasets/train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [4]:
# Get the names of columns with null values
null_columns = df.columns[df.isnull().any()]
# Create a new DataFrame with only the columns containing null values
df[null_columns].isnull().sum()

LotFrontage      259
Alley           1369
MasVnrType         8
MasVnrArea         8
BsmtQual          37
BsmtCond          37
BsmtExposure      38
BsmtFinType1      37
BsmtFinType2      38
Electrical         1
FireplaceQu      690
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
PoolQC          1453
Fence           1179
MiscFeature     1406
dtype: int64

we remove column those have null value > 500

In [5]:
df.drop(columns=['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'], inplace=True)
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [6]:
# Get the names of columns with null values
null_columns = df.columns[df.isnull().any()]
# Create a new DataFrame with only the columns containing null values
df[null_columns].isnull().sum()

LotFrontage     259
MasVnrType        8
MasVnrArea        8
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Electrical        1
GarageType       81
GarageYrBlt      81
GarageFinish     81
GarageQual       81
GarageCond       81
dtype: int64

In [7]:
df.drop(columns=['Id'], axis=1)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2008,WD,Normal,147500

now fill missing values.

In [8]:
# Fill null values with mean for each column
df_filled = df.fillna(df.mean())

# Display the DataFrame with null values filled by mean
df_filled

C:\Users\Dell\AppData\Local\Temp\ipykernel_6792\1097104169.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df_filled = df.fillna(df.mean())

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [9]:
# Find columns with missing values (True indicates missing values)
columns_with_missing_values = df.isnull().sum() > 0

columns_with_missing_values[columns_with_missing_values].index.tolist()

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [10]:
# List of specific columns for which you want to find unique values
specific_columns = ['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']  

# Initialize a dictionary to store unique values for each specific column
unique_values_dict = {}

# Iterate through the specific columns and find unique values
for column in specific_columns:
    unique_values = df[column].unique()
    mode_value = df[column].mode().iloc[0]  # Get the most common value (mode)
    unique_values_dict[column] = {
        'Unique Values': unique_values,
        'Most Common Value (Mode)': mode_value
    }

# Print unique values for each specific column
for column, values_info in unique_values_dict.items():
    print(f"Unique values for {column}:")
    print(f"Unique Values: {values_info['Unique Values']}")
    print(f"Most Common Value (Mode): {values_info['Most Common Value (Mode)']}\n")

Unique values for LotFrontage:
Unique Values: [ 65.  80.  68.  60.  84.  85.  75.  nan  51.  50.  70.  91.  72.  66.
 101.  57.  44. 110.  98.  47. 108. 112.  74. 115.  61.  48.  33.  52.
 100.  24.  89.  63.  76.  81.  95.  69.  21.  32.  78. 121. 122.  40.
 105.  73.  77.  64.  94.  34.  90.  55.  88.  82.  71. 120. 107.  92.
 134.  62.  86. 141.  97.  54.  41.  79. 174.  99.  67.  83.  43. 103.
  93.  30. 129. 140.  35.  37. 118.  87. 116. 150. 111.  49.  96.  59.
  36.  56. 102.  58.  38. 109. 130.  53. 137.  45. 106. 104.  42.  39.
 144. 114. 128. 149. 313. 168. 182. 138. 160. 152. 124. 153.  46.]
Most Common Value (Mode): 60.0

Unique values for MasVnrType:
Unique Values: ['BrkFace' 'None' 'Stone' 'BrkCmn' nan]
Most Common Value (Mode): None

Unique values for MasVnrArea:
Unique Values: [1.960e+02 0.000e+00 1.620e+02 3.500e+02 1.860e+02 2.400e+02 2.860e+02
 3.060e+02 2.120e+02 1.800e+02 3.800e+02 2.810e+02 6.400e+02 2.000e+02
 2.460e+02 1.320e+02 6.500e+02 1.010e+02 4.120e+02 2.720e+02 4.560e+02
 1.031e+03 1.780e+02 5.730e+02 3.440e+02 2.870e+02 1.670e+02 1.115e+03
 4.000e+01 1.040e+02 5.760e+02 4.430e+02 4.680e+02 6.600e+01 2.200e+01
 2.840e+02 7.600e+01 2.030e+02 6.800e+01 1.830e+02 4.800e+01 2.800e+01
 3.360e+02 6.000e+02 7.680e+02 4.800e+02 2.200e+02 1.840e+02 1.129e+03
 1.160e+02 1.350e+02 2.660e+02 8.500e+01 3.090e+02 1.360e+02 2.880e+02
 7.000e+01 3.200e+02 5.000e+01 1.200e+02 4.360e+02 2.520e+02 8.400e+01
 6.640e+02 2.260e+02 3.000e+02 6.530e+02 1.120e+02 4.910e+02 2.680e+02
 7.480e+02 9.800e+01 2.750e+02 1.380e+02 2.050e+02 2.620e+02 1.280e+02
 2.600e+02 1.530e+02 6.400e+01 3.120e+02 1.600e+01 9.220e+02 1.420e+02
 2.900e+02 1.270e+02 5.060e+02 2.970e+02       nan 6.040e+02 2.540e+02
 3.600e+01 1.020e+02 4.720e+02 4.810e+02 1.080e+02 3.020e+02 1.720e+02
 3.990e+02 2.700e+02 4.600e+01 2.100e+02 1.740e+02 3.480e+02 3.150e+02
 2.990e+02 3.400e+02 1.660e+02 7.200e+01 3.100e+01 3.400e+01 2.380e+02
 1.600e+03 3.650e+02 5.600e+01 1.500e+02 2.780e+02 2.560e+02 2.250e+02
 3.700e+02 3.880e+02 1.750e+02 2.960e+02 1.460e+02 1.130e+02 1.760e+02
 6.160e+02 3.000e+01 1.060e+02 8.700e+02 3.620e+02 5.300e+02 5.000e+02
 5.100e+02 2.470e+02 3.050e+02 2.550e+02 1.250e+02 1.000e+02 4.320e+02
 1.260e+02 4.730e+02 7.400e+01 1.450e+02 2.320e+02 3.760e+02 4.200e+01
 1.610e+02 1.100e+02 1.800e+01 2.240e+02 2.480e+02 8.000e+01 3.040e+02
 2.150e+02 7.720e+02 4.350e+02 3.780e+02 5.620e+02 1.680e+02 8.900e+01
 2.850e+02 3.600e+02 9.400e+01 3.330e+02 9.210e+02 7.620e+02 5.940e+02
 2.190e+02 1.880e+02 4.790e+02 5.840e+02 1.820e+02 2.500e+02 2.920e+02
 2.450e+02 2.070e+02 8.200e+01 9.700e+01 3.350e+02 2.080e+02 4.200e+02
 1.700e+02 4.590e+02 2.800e+02 9.900e+01 1.920e+02 2.040e+02 2.330e+02
 1.560e+02 4.520e+02 5.130e+02 2.610e+02 1.640e+02 2.590e+02 2.090e+02
 2.630e+02 2.160e+02 3.510e+02 6.600e+02 3.810e+02 5.400e+01 5.280e+02
 2.580e+02 4.640e+02 5.700e+01 1.470e+02 1.170e+03 2.930e+02 6.300e+02
 4.660e+02 1.090e+02 4.100e+01 1.600e+02 2.890e+02 6.510e+02 1.690e+02
 9.500e+01 4.420e+02 2.020e+02 3.380e+02 8.940e+02 3.280e+02 6.730e+02
 6.030e+02 1.000e+00 3.750e+02 9.000e+01 3.800e+01 1.570e+02 1.100e+01
 1.400e+02 1.300e+02 1.480e+02 8.600e+02 4.240e+02 1.047e+03 2.430e+02
 8.160e+02 3.870e+02 2.230e+02 1.580e+02 1.370e+02 1.150e+02 1.890e+02
 2.740e+02 1.170e+02 6.000e+01 1.220e+02 9.200e+01 4.150e+02 7.600e+02
 2.700e+01 7.500e+01 3.610e+02 1.050e+02 3.420e+02 2.980e+02 5.410e+02
 2.360e+02 1.440e+02 4.230e+02 4.400e+01 1.510e+02 9.750e+02 4.500e+02
 2.300e+02 5.710e+02 2.400e+01 5.300e+01 2.060e+02 1.400e+01 3.240e+02
 2.950e+02 3.960e+02 6.700e+01 1.540e+02 4.250e+02 4.500e+01 1.378e+03
 3.370e+02 1.490e+02 1.430e+02 5.100e+01 1.710e+02 2.340e+02 6.300e+01
 7.660e+02 3.200e+01 8.100e+01 1.630e+02 5.540e+02 2.180e+02 6.320e+02
 1.140e+02 5.670e+02 3.590e+02 4.510e+02 6.210e+02 7.880e+02 8.600e+01
 7.960e+02 3.910e+02 2.280e+02 8.800e+01 1.650e+02 4.280e+02 4.100e+02
 5.640e+02 3.680e+02 3.180e+02 5.790e+02 6.500e+01 7.050e+02 4.080e+02
 2.440e+02 1.230e+02 3.660e+02 7.310e+02 4.480e+02 2.940e+02 3.100e+02
 2.370e+02 4.260e+02 9.600e+01 4.380e+02 1.940e+02 1.190e+02]
Most Common Value (Mode): 0.0

Unique values for BsmtQual:
Unique Values: ['Gd' 'TA' 'Ex' nan 'Fa']
Most Common Value (Mode): TA

Unique values for BsmtCond:
Unique Values: ['TA' 'Gd' nan 'Fa' 'Po']
Most Common Value (Mode): TA

Unique values for BsmtExposure:
Unique Values: ['No' 'Gd' 'Mn' 'Av' nan]
Most Common Value (Mode): No

Unique values for BsmtFinType1:
Unique Values: ['GLQ' 'ALQ' 'Unf' 'Rec' 'BLQ' nan 'LwQ']
Most Common Value (Mode): Unf

Unique values for BsmtFinType2:
Unique Values: ['Unf' 'BLQ' nan 'ALQ' 'Rec' 'LwQ' 'GLQ']
Most Common Value (Mode): Unf

Unique values for Electrical:
Unique Values: ['SBrkr' 'FuseF' 'FuseA' 'FuseP' 'Mix' nan]
Most Common Value (Mode): SBrkr

Unique values for GarageType:
Unique Values: ['Attchd' 'Detchd' 'BuiltIn' 'CarPort' nan 'Basment' '2Types']
Most Common Value (Mode): Attchd

Unique values for GarageYrBlt:
Unique Values: [2003. 1976. 2001. 1998. 2000. 1993. 2004. 1973. 1931. 1939. 1965. 2005.
 1962. 2006. 1960. 1991. 1970. 1967. 1958. 1930. 2002. 1968. 2007. 2008.
 1957. 1920. 1966. 1959. 1995. 1954. 1953.   nan 1983. 1977. 1997. 1985.
 1963. 1981. 1964. 1999. 1935. 1990. 1945. 1987. 1989. 1915. 1956. 1948.
 1974. 2009. 1950. 1961. 1921. 1900. 1979. 1951. 1969. 1936. 1975. 1971.
 1923. 1984. 1926. 1955. 1986. 1988. 1916. 1932. 1972. 1918. 1980. 1924.
 1996. 1940. 1949. 1994. 1910. 1978. 1982. 1992. 1925. 1941. 2010. 1927.
 1947. 1937. 1942. 1938. 1952. 1928. 1922. 1934. 1906. 1914. 1946. 1908.
 1929. 1933.]
Most Common Value (Mode): 2005.0

Unique values for GarageFinish:
Unique Values: ['RFn' 'Unf' 'Fin' nan]
Most Common Value (Mode): Unf

Unique values for GarageQual:
Unique Values: ['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
Most Common Value (Mode): TA

Unique values for GarageCond:
Unique Values: ['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
Most Common Value (Mode): TA

In [11]:
# List of columns and their default values for filling
columns_to_fill = {
    'LotFrontage': 60.00,
    'MasVnrType': 'None',
    'MasVnrArea': 400.0,  # we see there are common power is 2 and looks like 4 is the average.
    'BsmtQual': 'TA',
    'BsmtCond': 'TA',
    'BsmtExposure': 'No',
    'BsmtFinType1': 'Unf',
    'BsmtFinType2': 'Unf',
    'Electrical': 'SBrkr',
    'GarageType': 'Attchd',
    'GarageYrBlt': 2005.0,
    'GarageFinish': 'Unf',
    'GarageQual': 'TA',
    'GarageCond': 'TA'
}

# Loop through the specified columns and fill null values with default values
for column, default_value in columns_to_fill.items():
    df[column].fillna(default_value, inplace=True)

In [12]:
# Find columns with missing values (True indicates missing values)
columns_with_missing_values = df.isnull().sum() > 0

columns_with_missing_values[columns_with_missing_values].index.tolist()

[]

In [13]:
# we need labal encoder
from sklearn.preprocessing import LabelEncoder

# Get a list of column names with non-numeric (categorical) data
categorical_columns = df.select_dtypes(include=['object']).columns

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Apply label encoding to each categorical column
for column in categorical_columns:
    df[column] = label_encoder.fit_transform(df[column])

In [14]:
y = df.iloc[:,75:]
x = df.drop(columns=['SalePrice'], axis=1)
y,x

(      SalePrice
 0        208500
 1        181500
 2        223500
 3        140000
 4        250000
 ...         ...
 1455     175000
 1456     210000
 1457     266500
 1458     142125
 1459     147500

 [1460 rows x 1 columns],
         Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
 0        1          60         3         65.0     8450       1         3
 1        2          20         3         80.0     9600       1         3
 2        3          60         3         68.0    11250       1         0
 3        4          70         3         60.0     9550       1         0
 4        5          60         3         84.0    14260       1         0
 ...    ...         ...       ...          ...      ...     ...       ...
 1455  1456          60         3         62.0     7917       1         3
 1456  1457          20         3         85.0    13175       1         3
 1457  1458          70         3         66.0     9042       1         3
 1458  1459          20         3         68.0     9717       1         3
 1459  1460          20         3         75.0     9937       1         3

       LandContour  Utilities  LotConfig  ...  OpenPorchSF  EnclosedPorch  \
 0               3          0          4  ...           61              0
 1               3          0          2  ...            0              0
 2               3          0          4  ...           42              0
 3               3          0          0  ...           35            272
 4               3          0          2  ...           84              0
 ...           ...        ...        ...  ...          ...            ...
 1455            3          0          4  ...           40              0
 1456            3          0          4  ...            0              0
 1457            3          0          4  ...           60              0
 1458            3          0          4  ...            0            112
 1459            3          0          4  ...           68              0

       3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
 0             0            0         0        0       2    2008         8
 1             0            0         0        0       5    2007         8
 2             0            0         0        0       9    2008         8
 3             0            0         0        0       2    2006         8
 4             0            0         0        0      12    2008         8
 ...         ...          ...       ...      ...     ...     ...       ...
 1455          0            0         0        0       8    2007         8
 1456          0            0         0        0       2    2010         8
 1457          0            0         0     2500       5    2010         8
 1458          0            0         0        0       4    2010         8
 1459          0            0         0        0       6    2008         8

       SaleCondition
 0                 4
 1                 4
 2                 4
 3                 0
 4                 4
 ...             ...
 1455              4
 1456              4
 1457              4
 1458              4
 1459              4

 [1460 rows x 75 columns])

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)

In [16]:
x_train.describe()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
count,1168.000000,1168.000000,1168.000000,1168.000000,1168.00000,1168.000000,1168.000000,1168.000000,1168.0,1168.000000,...,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000,1168.000000
mean,728.628425,56.660959,3.015411,68.559075,10662.07363,0.994863,1.973459,2.760274,0.0,3.000856,...,45.434932,21.112158,3.797089,14.796233,2.955479,44.515411,6.249144,2007.818493,7.504281,3.753425
std,425.764615,41.945283,0.647798,23.052749,10900.47878,0.071519,1.397812,0.731748,0.0,1.631681,...,65.821908,60.403061,30.903988,55.668482,41.648504,497.493444,2.697947,1.339378,1.572029,1.128803
min,1.000000,20.000000,0.000000,21.000000,1477.00000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,0.000000,0.000000
25%,361.750000,20.000000,3.000000,60.000000,7589.50000,1.000000,0.000000,3.000000,0.0,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,8.000000,4.000000
50%,726.500000,50.000000,3.000000,64.000000,9451.00000,1.000000,3.000000,3.000000,0.0,4.000000,...,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,8.000000,4.000000
75%,1098.250000,70.000000,3.000000,79.000000,11475.00000,1.000000,3.000000,3.000000,0.0,4.000000,...,66.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,8.000000,4.000000
max,1460.000000,190.000000,4.000000,313.000000,215245.00000,1.000000,3.000000,3.000000,0.0,4.000000,...,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,8.000000,5.000000

###  here is big differnce in columns values we need StandardScaler

In [17]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit and transform the entire DataFrame
x_train = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
x_test = pd.DataFrame(scaler.fit_transform(x_test), columns=x_test.columns)

In [18]:
x_train.describe()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
count,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1168.0,1.168000e+03,...,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03,1.168000e+03
mean,1.351659e-16,-1.024437e-16,-5.625732e-16,1.619709e-16,-6.202231e-17,-6.084127e-16,3.288846e-17,8.364694e-17,0.0,5.104364e-17,...,-2.146304e-16,-1.172008e-16,-1.827638e-16,5.094859e-17,3.115136e-16,-2.596857e-16,-8.571435e-17,6.529402e-14,3.487507e-16,-1.518002e-16
std,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,0.0,1.000428e+00,...,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00,1.000428e+00
min,-1.709724e+00,-8.743930e-01,-4.656857e+00,-2.063938e+00,-8.429912e-01,-1.391642e+01,-1.412424e+00,-3.773779e+00,0.0,-1.839908e+00,...,-6.905663e-01,-3.496710e-01,-1.229199e-01,-2.659058e-01,-7.099284e-02,-8.951772e-02,-1.946440e+00,-1.358296e+00,-4.775672e+00,-3.326562e+00
25%,-8.620622e-01,-8.743930e-01,-2.379995e-02,-3.714412e-01,-2.819959e-01,7.185758e-02,-1.412424e+00,3.277475e-01,0.0,-6.136525e-01,...,-6.905663e-01,-3.496710e-01,-1.229199e-01,-2.659058e-01,-7.099284e-02,-8.951772e-02,-8.340071e-01,-6.113612e-01,3.154722e-01,2.185333e-01
50%,-5.001206e-03,-1.588692e-01,-2.379995e-02,-1.978518e-01,-1.111504e-01,7.185758e-02,7.347058e-01,3.277475e-01,0.0,6.126026e-01,...,-3.257899e-01,-3.496710e-01,-1.229199e-01,-2.659058e-01,-7.099284e-02,-8.951772e-02,-9.238526e-02,1.355738e-01,3.154722e-01,2.185333e-01
75%,8.685078e-01,3.181467e-01,-2.379995e-02,4.531085e-01,7.460907e-02,7.185758e-02,7.347058e-01,3.277475e-01,0.0,6.126026e-01,...,3.125688e-01,-3.496710e-01,-1.229199e-01,-2.659058e-01,-7.099284e-02,-8.951772e-02,6.492366e-01,8.825088e-01,3.154722e-01,2.185333e-01
max,1.718520e+00,3.180242e+00,1.520552e+00,1.060809e+01,1.877629e+01,7.185758e-02,7.347058e-01,3.277475e-01,0.0,6.126026e-01,...,7.623296e+00,8.792853e+00,1.632213e+01,8.360261e+00,1.765632e+01,3.108002e+01,2.132480e+00,1.629444e+00,3.154722e-01,1.104807e+00

In [19]:
x_test.describe()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
count,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,292.0,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,...,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02,2.920000e+02
mean,6.615713e-17,3.003686e-17,1.138739e-16,-2.290786e-16,-5.779243e-17,0.0,-8.668865e-17,3.954219e-17,7.143259e-17,9.733462e-17,...,-2.661494e-17,4.448496e-17,-2.404850e-17,-6.995926e-17,3.455189e-17,-1.040834e-16,8.212609e-17,-8.746618e-14,-2.555034e-16,4.885742e-17
std,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,0.0,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,...,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00,1.001717e+00
min,-1.797276e+00,-8.663789e-01,-5.490255e+00,-2.391039e+00,-1.820988e+00,0.0,-1.256746e+00,-4.767131e+00,-5.862104e-02,-1.952502e+00,...,-7.611467e-01,-3.969578e-01,-8.535727e-02,-2.873470e-01,-5.862104e-02,-8.027855e-02,-2.073742e+00,-1.407848e+00,-5.137320e+00,-3.924405e+00
25%,-8.856417e-01,-8.663789e-01,-1.464068e-01,-3.682211e-01,-5.686675e-01,0.0,-1.256746e+00,2.581479e-01,-5.862104e-02,-6.897543e-01,...,-7.611467e-01,-3.969578e-01,-8.535727e-02,-2.873470e-01,-5.862104e-02,-8.027855e-02,-5.959319e-01,-6.277882e-01,3.076798e-01,1.645380e-01
50%,2.599226e-02,-1.795482e-01,-1.464068e-01,-3.682211e-01,-7.081778e-02,0.0,8.165297e-01,2.581479e-01,-5.862104e-02,5.729934e-01,...,-3.035285e-01,-3.969578e-01,-8.535727e-02,-2.873470e-01,-5.862104e-02,-8.027855e-02,-2.264794e-01,1.522720e-01,3.076798e-01,1.645380e-01
75%,8.337927e-01,2.783389e-01,-1.464068e-01,5.264870e-01,4.352557e-01,0.0,8.165297e-01,2.581479e-01,-5.862104e-02,5.729934e-01,...,3.349228e-01,-3.969578e-01,-8.535727e-02,-2.873470e-01,-5.862104e-02,-8.027855e-02,5.124255e-01,9.323323e-01,3.076798e-01,1.645380e-01
max,1.760260e+00,3.025662e+00,1.634876e+00,5.544632e+00,9.186952e+00,0.0,8.165297e-01,2.581479e-01,1.705872e+01,5.729934e-01,...,5.232176e+00,4.196243e+00,1.386859e+01,6.771609e+00,1.705872e+01,1.683825e+01,1.990235e+00,1.712392e+00,3.076798e-01,1.186774e+00

### reduce column for x

In [21]:
from sklearn.decomposition import PCA

n_components = 5  # Set the number of components you want to keep
pca = PCA(n_components=n_components)

x_train_pca = pca.fit_transform(x_train)
x_test_pca = pca.transform(x_test)

In [24]:
# Create DataFrames for the principal components
principal_train_df = pd.DataFrame(data=x_train_pca, columns=[f'PC{i}' for i in range(1, n_components + 1)])
principal_test_df = pd.DataFrame(data=x_test_pca, columns=[f'PC{i}' for i in range(1, n_components + 1)])

In [25]:
principal_train_df

           PC1       PC2        PC3       PC4       PC5
0    -5.395251  4.408898  -0.055102  1.072412  3.942704
1     2.761102 -0.553759  12.532617  2.579615  2.286387
2    -4.919448  2.445640   0.427668 -3.128790  0.673483
3    -4.207172  2.224589  -0.390131 -0.526983 -1.071977
4    -4.275394 -0.792164  -0.994123 -2.554890 -1.288945
...        ...       ...        ...       ...       ...
1163 -2.089315 -1.442918  -2.088049  3.761892  1.655012
1164 -0.938250  2.715584  -1.591065  1.854624  0.772941
1165  1.182312 -0.819545  -3.865898  2.942943  2.059263
1166  1.297822 -0.829955   1.456727  1.805752  0.732376
1167 -2.483485  3.951167   0.862367 -1.011803 -1.910489

[1168 rows x 5 columns]

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and fit the linear regression model
regression_model = LinearRegression()
regression_model.fit(principal_train_df, y_train)

# Predict on the test set
y_pred = regression_model.predict(principal_test_df)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Linear Regression Metrics:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

Linear Regression Metrics:
Mean Squared Error (MSE): 1368454207.54634
R-squared (R2): 0.781638871229625

In [27]:
from sklearn.linear_model import Ridge

# Initialize and fit the Ridge regression model
ridge_model = Ridge(alpha=1.0)
ridge_model.fit(principal_train_df, y_train)

# Predict on the test set
y_pred = ridge_model.predict(principal_test_df)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Ridge Regression Metrics:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

Ridge Regression Metrics:
Mean Squared Error (MSE): 1368406648.423578
R-squared (R2): 0.7816464601307899

In [28]:
from sklearn.linear_model import Lasso

# Initialize and fit the Lasso regression model
lasso_model = Lasso(alpha=1.0)
lasso_model.fit(principal_train_df, y_train)

# Predict on the test set
y_pred = lasso_model.predict(principal_test_df)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Lasso Regression Metrics:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

Lasso Regression Metrics:
Mean Squared Error (MSE): 1368447363.6596458
R-squared (R2): 0.7816399632930755

In [30]:
from sklearn.ensemble import RandomForestRegressor

# Initialize and fit the Random Forest regression model
rf_model = RandomForestRegressor(n_estimators=200, random_state=42)
rf_model.fit(principal_train_df, y_train)

# Predict on the test set
y_pred = rf_model.predict(principal_test_df)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Random Forest Regression Metrics:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

C:\Users\Dell\AppData\Local\Temp\ipykernel_6792\3135274989.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(principal_train_df, y_train)

Random Forest Regression Metrics:
Mean Squared Error (MSE): 1208296297.4413173
R-squared (R2): 0.8071949050663312

In [34]:
from sklearn.ensemble import RandomForestRegressor

# Initialize and fit the Random Forest regression model
rf_model = RandomForestRegressor(n_estimators=200, random_state=42)
rf_model.fit(x_train, y_train)

# Predict on the test set
y_pred = rf_model.predict(x_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Random Forest Regression Metrics:")
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")

C:\Users\Dell\AppData\Local\Temp\ipykernel_6792\3659174020.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(x_train, y_train)

Random Forest Regression Metrics:
Mean Squared Error (MSE): 1049909414.9737204
R-squared (R2): 0.8324683400467077

## for saving file do this
* output = pd.DataFrame({'Id': test.Id, 'SalePrice': y_pred})
* output.to_csv('submission.csv', index=False)